version: '2'
services:
    jhipsterdemo2-app:
        image: jhipsterdemo2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterdemo2-mysql:3306/jhipsterdemo2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterdemo2-mysql:
        extends:
            file: mysql.yml
            service: jhipsterdemo2-mysql
